[package]
name = "punks-browser"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
punks-core = { path = "../punks-core" }
punks-playback = { path = "../punks-playback" }
